theme = "awesome-identity"
baseURL = "https://rudesome.nl"
title = "âžœ  ~ whoami"
publishDir = "docs"
disableKinds = ["taxonomy", "term"]

## Profile Configurations
[params.profile]
  portrait = "/images/portrait.png"
  firstname = "Ruud"
  lastname = "Voorjans"
  title = "Software / DevOps Engineer"
  location = "Simpelveld"
  bio = """
  I am a DevOps engineer with 10+ years of sysadmin experience. <br> 
In my day job, I automate the business with custom developed software,
and using techniques like Ansible, Docker and Kubernetes <br> <br>
At night am mainly "z-shelling" in the terminal; writing, coding, reading, deploying and learning. <br>
Passionate about Programming, Open Source and (good) IT Design."""

[params.contacts]
  email = "ruud.voorjans@rudesome.nl"
  github = "rudesome"
  linkedin = "rudesome"

[params.actions.resume]
  name = "Resume"
  url = "/resume"

[params.actions.source]
  name = "Site Source"
  url = "https://github.com/rudesome/cv.parkhost.eu"

## Footer Configurations
[params.footer]
  copyright = """<i class="fab fa-linux"></i> *Ruud Voorjans* <i class="fab fa-linux"></i>"""
  poweredBy = false

[markup.goldmark.renderer]
unsafe= true

