theme = "awesome-identity"
baseURL = "https://parkhost.github.io/cv.parkhost.eu/"
title = "~ whoami"
publishDir = "docs"
disableKinds = ["taxonomy", "term"]

## Profile Configurations
[params.profile]
  portrait = "/images/portrait.png"
  firstname = "Ruud"
  lastname = "Voorjans"
  title = "System Adminstrator, Software / DevOps Engineer"
  location = "Simpelveld"
  bio = """I am a experienced system administrator. In my day job, I develop automation frameworks in PowerShell and Python. Passionate about Software, Automation and Creating (customer) services."""

[params.contacts]
  email = "ruud.voorjans@parkhost.eu"
  github = "parkhost"
  linkedin = "parkhost"

[params.actions.resume]
  name = "Resume"
  url = "/cv.parkhost.eu/resume"

[params.actions.source]
  name = "Site Source"
  url = "https://github.com/parkhost/cv.parkhost.eu"

## Footer Configurations
[params.footer]
  copyright = """<i class="fab fa-linux"></i>I use 'Linux', btw<i class="fab fa-linux"></i>"""
  poweredBy = false

[markup.goldmark.renderer]
unsafe= true

